# Generated by Django 4.0.5 on 2022-07-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('specialist', models.CharField(choices=[('PPC', 'PPC'), ('Digital', 'Digital')], max_length=10, verbose_name='Специалист')),
                ('is_company', models.BooleanField(default=False, verbose_name='Это компания?')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Имя')),
                ('username', models.CharField(max_length=256, unique=True, verbose_name='Почта')),
                ('phone_number', models.CharField(blank=True, max_length=18, null=True, verbose_name='Номер телефона')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(blank=True, choices=[('Man', 'Man'), ('Woman', 'Woman')], max_length=10, null=True, verbose_name='Пол')),
                ('description', models.CharField(blank=True, max_length=999, null=True, verbose_name='Описание')),
                ('company_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Название')),
                ('site', models.CharField(blank=True, max_length=256, null=True, verbose_name='Сайт компании')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата редактирования')),
                ('is_staff', models.BooleanField(default=False, help_text='Открывает доступ к панели администратора с указанными правами', verbose_name='Сотрудник организации')),
                ('is_active', models.BooleanField(default=True, help_text='Статус (по умолчанию "Да")', verbose_name='Активный аккаунт')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь системы',
                'verbose_name_plural': 'Пользователи системы',
                'ordering': ('-created_at',),
            },
        ),
    ]
